{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fenwave-backstage.secretName" . }}
  labels:
    {{- include "fenwave-backstage.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.secretValues.POSTGRES_PASSWORD | b64enc | quote }}
  backend-secret: {{ .Values.secretValues.BACKEND_SECRET | b64enc | quote }}
  {{- if .Values.secretValues.GITHUB_TOKEN }}
  github-token: {{ .Values.secretValues.GITHUB_TOKEN | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretValues.ARGOCD_TOKEN }}
  argocd-token: {{ .Values.secretValues.ARGOCD_TOKEN | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretValues.KUBERNETES_SERVICE_ACCOUNT_TOKEN }}
  service-account-token: {{ .Values.secretValues.KUBERNETES_SERVICE_ACCOUNT_TOKEN | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretValues.KUBERNETES_SERVICE_ACCOUNT_CA_DATA }}
  service-account-ca-data: {{ .Values.secretValues.KUBERNETES_SERVICE_ACCOUNT_CA_DATA | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretValues.ARGO_WORKFLOWS_TOKEN }}
  argo-workflows-token: {{ .Values.secretValues.ARGO_WORKFLOWS_TOKEN | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretValues.AUTH_GITHUB_CLIENT_ID }}
  auth-github-client-id: {{ .Values.secretValues.AUTH_GITHUB_CLIENT_ID | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretValues.AUTH_GITHUB_CLIENT_SECRET }}
  auth-github-client-secret: {{ .Values.secretValues.AUTH_GITHUB_CLIENT_SECRET | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretValues.AUTH_BITBUCKET_CLIENT_ID }}
  auth-bitbucket-client-id: {{ .Values.secretValues.AUTH_BITBUCKET_CLIENT_ID | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretValues.AUTH_BITBUCKET_CLIENT_SECRET }}
  auth-bitbucket-client-secret: {{ .Values.secretValues.AUTH_BITBUCKET_CLIENT_SECRET | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretValues.BACKSTAGE_BASE_URL }}
  backstage-base-url: {{ .Values.secretValues.BACKSTAGE_BASE_URL | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretValues.BACKSTAGE_BACKEND_URL }}
  backstage-backend-url: {{ .Values.secretValues.BACKSTAGE_BACKEND_URL | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretValues.KUBERNETES_SERVICE_ACCOUNT_TOKEN }}
  kubernetes-service-account-token: {{ .Values.secretValues.KUBERNETES_SERVICE_ACCOUNT_TOKEN | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretValues.KUBERNETES_SERVICE_ACCOUNT_CA_DATA }}
  kubernetes-service-account-ca-data: {{ .Values.secretValues.KUBERNETES_SERVICE_ACCOUNT_CA_DATA | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretValues.JENKINS_API_KEY }}
  jenkins-api-key: {{ .Values.secretValues.JENKINS_API_KEY | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretValues.SENTRY_DSN }}
  sentry-dsn: {{ .Values.secretValues.SENTRY_DSN | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretValues.SONARQUBE_API_KEY }}
  sonarqube-api-key: {{ .Values.secretValues.SONARQUBE_API_KEY | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretValues.PROMETHEUS_TOKEN }}
  prometheus-token: {{ .Values.secretValues.PROMETHEUS_TOKEN | b64enc | quote }}
  {{- end }}
{{- end }}
